#!/bin/sh
clear
#javac -d cls  src/tg37/tinyc/TJ.java 2> errs
#javac -d cls src/tg37/tinyc/Stuff.java 2>> errs 
#javac -d cls src/tg37/tinyc/Stack.java 2>> errs
#javac -d cls src/tg37/tinyc/PT.java 2> errs
javac -d cls src/tg37/tinyc/Expr.java 2>> errs
#javac -d cls src/tg37/tinyc/*.java 2>> errs

head errs -n 20


#Remember: >> for multiple compiles
#And > for single
